### ISSUE TITLE
required() message

### ISSUE THREAD

**Issue by gassius** [marvinlabs/laravel-workbench#1]
Hi, I am sorry to post this as an issue, but I haven't found any information after looking here and on spatie/laravel-html repo

I am using this package to create some forms and I am using the required() method to validate some things before submission. It does work, but the message is in English, and I would like to display a custom message.  I tried to pass a string within the method call, but it did not change the message. Also reviewed the src of this package and laravel-html to see if there is any reference to this method and could not find anything. 

Could you please help me out with this? To be clear I am using something like:

` bs()->formGroup(bs()->text('name')->required('Customs message')`

Thanks in advance

**Comment by gassius** [comment]
Totally sorry, now I realize this is done via ContrainValidation. It could be a nice addition for a future feature. Regards

**Comment by vpratfr** [comment]
Hi

This does nothing more than adding a required attribute on the html field. 

All the validation is left to you. Custom messages should be passed according to Laravel conventions.

Glad you like the package.
